---
title: "Intro_keras"
author: "Bakro"
date: "1/3/2022"
output: 
  html_document:
   toc: true
   toc_float: true
   toc_depth: 3
   theme: flatly
   highlight: zenburn
   df_print: paged
   code_folding: hide 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intro_keras

```{r warning=FALSE , message=FALSE}
# install.packages("keras")
# devtools::install_github("rstudio/tensorflow")
# library(tensorflow)
# install_tensorflow(version = "2.0.01b")
# use_condaenv("ML_workshop")
# use_python(Sys.getenv("CONDA_PERFIX"))
# install.packages("keras")
library(keras)
library(tidyverse)
library(tensorflow)
```

## load data

```{r}
mnist <- dataset_mnist()
```

## example

```{r}
d = mnist$train$x[1,,]
plot(as.raster(d, max = 255))
mnist$train$y[1]
```

## normalize data

```{r}
mnist$train$x <- mnist$train$x/255
mnist$test$x <- mnist$test$x/255
```

## define model

```{r warning=FALSE ,message=FALSE}
model <- keras_model_sequential() %>% 
  layer_flatten(input_shape = c(28, 28)) %>% 
  layer_dense(units = 128, activation = "relu") %>% 
  layer_dropout(0.2) %>% 
  layer_dense(10, activation = "softmax")
```

```{r}
summary(model)
```

## compile model

```{r}
model %>% 
  compile(
    loss = "sparse_categorical_crossentropy",
    optimizer = "adam",
    metrics = "accuracy"
  )
```

## Fit model

```{r}
model %>% 
  fit(
    x = mnist$train$x, y = mnist$train$y,
    epochs = 5,
    validation_split = 0.3,
    verbose = 2
  )
```

## predict

```{r}
predictions <- predict(model, mnist$test$x)
head(predictions, 2)
```

## evaluate

```{r}
model %>% 
  evaluate(mnist$test$x, mnist$test$y, verbose = 0)
```

## save model

```{r}
save_model_tf(object = model, filepath = "model")
```

## Load model

```{r}
reloaded_model <- load_model_tf("model")
all.equal(predict(model, mnist$test$x), predict(reloaded_model, mnist$test$x))
```
