---
output: html_document
runtime: shiny
---

## inform 
goal of this project is to convert cyclist from casual to member cyclist 
one of tasks find best campaign method that is posters where is the most traffic 
cyclist , i have convert this project to show it in leaflet and shiny 


```{r  echo=FALSE , message=FALSE}
## read data (we have alraedy summarise this data)
library(tidyverse)
library(leaflet)
 df <- read.csv(file = "./data/summary_stations.csv")
 df <- df[-nrow(df),] # remove last row 
# skimr::skim_without_charts(df)
colnames(df)[3:4] <- c("lat" ,"lng") 
## processing data
df2 <- data.frame(lat =df$lat , lng =df$lng ,name = df$stations.end_station_name 
                  ,traffic_causual = df$trafficstartbycustomer.traffic_begin_casual
                                    + df$trafficendbycustomer.traffic_end_casual
                  ,traffic_member =df$trafficstartbycustomer.traffic_begin_member
                                    + df$trafficendbycustomer.traffic_end_member
                  ,alltraffic = df$trafficstartbycustomer.traffic_begin +
                                df$trafficendbycustomer.traffic_end) 
# str(df2)

## set view 
lng <- mean(df$lng , na.rm = TRUE)
lat <- mean(df$lat , na.rm = TRUE)
rm(df)
```



```{r echo=FALSE}
library(shiny)
library(dplyr)
# Define UI for dataset viewer app ----
ui <- fluidPage(

  # App title ----
  titlePanel("Shiny and leaflet 16/11/2021"),

  # Sidebar layout with a input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      # Input: Selector for choosing dataset ----
      selectInput(inputId = "cyclist_type",
                  label = "Choose type of cyclist : ",
                  choices = c("member", "casual", "all")),

      # Input: Numeric entry for number of obs to view ----
      numericInput(inputId = "traffic",
                   label = "station traffic:",
                   value = 250) ,
       numericInput(inputId = "top",
                   label = "top traffic station:",
                   value = 731 ,min = 10 , max = 731)
    ),

    # Main panel for displaying outputs ----
    mainPanel(

      leafletOutput("mymap")
    )
  )
)



# Define server logic to summarize and view selected dataset ----
server <- function(input, output) {

  # Return the requested dataset ----
  cyclist_type_Input <- reactive({
  #    switch(input$cyclist_type,
  #           "member" = "1",
  #           "casual" = "2",
  #           "all" = "3")
    if (input$cyclist_type == "member") {return(paste("member"))
    }else if (input$cyclist_type == "casual") {return(paste("casual"))
    }else  if (input$cyclist_type == "all") {return(paste("all"))
    }

  })
  
  
output$mymap <- renderLeaflet({
  z <- as.character(cyclist_type_Input() )
  if(z == "member"){
     df2 %>% filter(traffic_member > as.numeric(input$traffic)) %>%
        top_n(input$top) %>% 
        leaflet() %>%
         addTiles() %>%
         addCircleMarkers( radius = df2$traffic_member*25/max(df2$traffic_member,na.rm = T) 
      ,popup =paste(df2$name ,paste("Traffic members " ,df2$traffic_member),sep = "<br/>")) %>%
         setView(lng= lng,lat = lat ,zoom = 10)
  } else if(z == "casual"){
    df2 %>%  filter(traffic_causual > input$traffic) %>% leaflet() %>%
         addTiles() %>%
         addCircleMarkers( radius = df2$traffic_causual*25/max(df2$traffic_causual,na.rm = T ),popup =
                    paste(df2$name ,paste("Traffic casual " ,df2$traffic_causual),sep = "<br/>")) %>%
         setView(lng= lng,lat = lat ,zoom = 10)
  } else if (z == "all"){
   df2 %>%  filter(alltraffic > input$traffic) %>% leaflet() %>% 
         addTiles() %>%
   addCircleMarkers( radius = df2$alltraffic*25/max(df2$alltraffic,na.rm = T ),popup =
                    paste(df2$name ,paste("alltraffic " ,df2$alltraffic),sep = "<br/>")) %>%
         setView(lng= lng,lat = lat ,zoom = 10)
  }
  

 
  
        
         })  
  
}

# Create Shiny app ----
shinyApp(ui = ui, server = server)


# https://z4ad3g-abdulmajid-bakro.shinyapps.io/shiny_leaflet/
```









